### ISSUE TITLE
Cannot compile anymore with version 2.7.7 (2.7.6 works fine)

### ISSUE THREAD

**Issue by lufo88ita** [danrevah/ngx-pipes#213]
**I'm submitting a ...**  (check one with "x")
```
[ x ] bug report => search github for a similar issue or PR before submitting
[ ] feature request
```

* **Ngx-pipes version:** 2.7.7

**Current behavior**
If you try to build in Angular 11 it fails.
Error:

```
Error: ./node_modules/ngx-pipes/fesm2015/ngx-pipes.mjs 1804:21-42
Can't import the named export 'ɵɵngDeclareFactory' from non EcmaScript module (only default export is available)
    at HarmonyImportSpecifierDependency._getErrors (<path-to-my-project>\platform\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:88:6)
    at HarmonyImportSpecifierDependency.getErrors (<path-to-my-project>\platform\ClientApp\node_modules\webpack\lib\dependencies\HarmonyImportSpecifierDependency.js:68:16)
    at Compilation.reportDependencyErrorsAndWarnings (<path-to-my-project>\platform\ClientApp\node_modules\webpack\lib\Compilation.js:1463:22)
    at <path-to-my-project>\platform\ClientApp\node_modules\webpack\lib\Compilation.js:1258:10
    at _next0 (eval at create (<path-to-my-project>\platform\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:32:1)
    at eval (eval at create (<path-to-my-project>\platform\ClientApp\node_modules\webpack\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:45:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
 @ ./src/app/components/<path-to-compenent>/<components>.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi ./src/main.ts
```

**Expected behavior**
Compile without problem

**Minimal reproduction of the problem with instructions**
Use ngx-pipes 2.7.7 with angular 11. With ngx-pipes 2.7.6 I have no problem

**Please tell us about your environment:**
Windows 10
IDE: visual studio code

* **Angular version:** 11.2.14

* **Node (for AoT issues):** `node --version` =   14.18.3

**Comment by danrevah** [comment]
This happened due to the upgrade to support Angular13: https://github.com/danrevah/ngx-pipes/pull/206

Reverted in v2.7.8 and Angular13 is supported via version Ngx-Pipes v3+.

**Comment by lufo88ita** [comment]
Thanks. I'm planning to upgrade my application to angular 12 and then angular 13. Good to know.
