### ISSUE TITLE
can't run the solution 

### ISSUE THREAD

**Issue by mohamedfathii** [danrevah/ngx-pipes#34]
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at createSourceFile (F:\ngx-pipes-master\node_modules\typescript\lib\typescript.js:9273:110)
    at parseSourceFileWorker (F:\ngx-pipes-master\node_modules\typescript\lib\typescript.js:9231:26)
    at Object.parseSourceFile (F:\ngx-pipes-master\node_modules\typescript\lib\typescript.js:9186:26)
    at Object.createSourceFile (F:\ngx-pipes-master\node_modules\typescript\lib\typescript.js:9011:29)
    at new TypeScriptFileRefactor (F:\ngx-pipes-master\node_modules\@ngtools\webpack\src\refactor.js:30:35)
    at Object.resolveEntryModuleFromMain (F:\ngx-pipes-master\node_modules\@ngtools\webpack\src\entry_resolver.js:105:20)
    at AotPlugin._setupOptions (F:\ngx-pipes-master\node_modules\@ngtools\webpack\src\plugin.js:138:50)
    at new AotPlugin (F:\ngx-pipes-master\node_modules\@ngtools\webpack\src\plugin.js:23:14)
    at _createAotPlugin (F:\ngx-pipes-master\node_modules\@angular\cli\models\webpack-configs\typescript.js:55:12)
    at Object.exports.getNonAotConfig (F:\ngx-pipes-master\node_modules\@angular\cli\models\webpack-configs\typescript.js:70:19)
    at NgCliWebpackConfig.buildConfig (F:\ngx-pipes-master\node_modules\@angular\cli\models\webpack-config.js:27:37)
    at Class.run (F:\ngx-pipes-master\node_modules\@angular\cli\tasks\serve.js:37:98)
    at check_port_1.checkPort.then.port (F:\ngx-pipes-master\node_modules\@angular\cli\commands\serve.js:103:26)
    at process._tickCallback (internal/process/next_tick.js:103:7)
PS F:\ngx-pipes-master>

**Comment by danrevah** [comment]
Can you explain what exactly did you do?

**Comment by mohamedfathii** [comment]
i have installed the angular cli packages and when i start to run the app with ng serve this error appear

**Comment by danrevah** [comment]
It doesn't look like you installed the `ngx-pipes` lib on your project it looks like you cloned it..  ("F:\ngx-pipes-master\").

Are you trying to clone the `ngx-pipes` project? 
If so: https://github.com/danrevah/ngx-pipes#contributing

**Comment by danrevah** [comment]
I'm closing this since there wasn't any response for the last 10 days.
If you still need my assistance reopen this issue and provide additional details.

Thanks.
